In [1]:
import pandas as pd

In [2]:
data_news = pd.read_csv(r"C:\Users\mahmo\OneDrive\Desktop\my work\KBH_TEAM\project_news\NewsCategorizer.csv", encoding='ISO-8859-1')

In [3]:
data_news.head(30)

,category,headline,links,short_description,keywords
0,WELLNESS,143 Miles in 35 Days: Lessons Learned,https://www.huffingtonpost.com/entry/running-l...,Resting is part of training. I've confirmed wh...,running-lessons
1,WELLNESS,Talking to Yourself: Crazy or Crazy Helpful?,https://www.huffingtonpost.com/entry/talking-t...,Think of talking to yourself as a tool to coac...,talking-to-yourself-crazy
2,WELLNESS,Crenezumab: Trial Will Gauge Whether Alzheimer...,https://www.huffingtonpost.com/entry/crenezuma...,The clock is ticking for the United States to ...,crenezumab-alzheimers-disease-drug
3,WELLNESS,"Oh, What a Difference She Made",https://www.huffingtonpost.com/entry/meaningfu...,"If you want to be busy, keep trying to be perf...",meaningful-life
4,WELLNESS,Green Superfoods,https://www.huffingtonpost.com/entry/green-sup...,"First, the bad news: Soda bread, corned beef a...",green-superfoods
5,WELLNESS,Bad Love Advice: 9 Lessons To Unlearn,https://www.huffingtonpost.com/entry/bad-love-...,"By Carey Moss for YouBeauty.com Love rom-coms,...",bad-love-advice-from-movies
6,WELLNESS,The Happiest (And Unhappiest) States In The U.S.,https://www.huffingtonpost.com/entry/happiest-...,The nation in general scored a 66.2 in 2011 on...,happiest-state-well-being-united-states-gallup
7,WELLNESS,Seaweed: The Green Superfood You're Not Eating...,https://www.huffingtonpost.com/entry/superfood...,It's also worth remembering that if the water ...,superfood-seaweed-health-benefits
8,WELLNESS,Addicted to Food?,https://www.huffingtonpost.com/entry/food-addi...,"If you look at our culture's eating behavior, ...",food-addiction
9,WELLNESS,High Tech Works When It Enables High Touch,https://www.huffingtonpost.com/entry/high-tech...,"FranÃ§ois-Marie Arouet, 18th century French au...",high-tech-works-when-it-e
10,WELLNESS,Conflict: 7 Decisions to Learn Instead of Fight,https://www.huffingtonpost.com/entry/conflict-...,If the other person never opens to caring conf...,conflict-resolution
11,WELLNESS,The Case For Lifting Heavy (VIDEO),https://www.huffingtonpost.com/entry/heavy-lif...,And the benefits are more than skin deep. Anni...,heavy-lifting-video
12,WELLNESS,A Show of Kindness: Good Works? Whatever Works,https://www.huffingtonpost.com/entry/philanthr...,I once wrestled -- for about four minutes -- w...,philanthropy
13,WELLNESS,Time to Sweep Up the Confetti and Start Saving...,https://www.huffingtonpost.com/entry/food-poli...,The Obama administration should use the next f...,food-policy
14,WELLNESS,Mysterious Illness at Le Roy School: Understan...,https://www.huffingtonpost.com/entry/le-roy-il...,"Recently, the media has burst with stories abo...",le-roy-illness
15,WELLNESS,At the Top of My Lungs: In Sickness and In Health,https://www.huffingtonpost.com/entry/living-wi...,"My heart is full when I look at my beautiful, ...",living-with-cancer
16,WELLNESS,The Most Beautiful Places To Nap (PHOTOS),https://www.huffingtonpost.com/entry/places-to...,"For more GPS Guides, click here. Feeling unins...",places-to-take-a-nap
17,WELLNESS,Are Antibiotics Making Us Fat?,https://www.huffingtonpost.com/entry/antibioti...,"Cleanliness may be next to godliness, but it m...",antibiotics-health
18,WELLNESS,Fearless Children Can Inspire a Nation,https://www.huffingtonpost.com/entry/fearless-...,I know that whether my children rise to dizzyi...,fearless-parenting
19,WELLNESS,Paper-Centered Care,https://www.huffingtonpost.com/entry/papercent...,There is a lot of talk in health care today ab...,papercentered-care
20,WELLNESS,Glenwood Gardens Case Provides a Teaching Mome...,https://www.huffingtonpost.com/entry/glenwood-...,Bystander intervention can mean the difference...,glenwood-gardens-case
21,WELLNESS,Overcoming the Naysayers and Sabotagers on You...,https://www.huffingtonpost.com/entry/weight-lo...,Dealing with these nuisances is rarely a laugh...,weight-loss-tips
22,WELLNESS,Pesticides and Personal Care Products Pollute ...,https://www.huffingtonpost.com/entry/natural-h...,The truth is that the more we know about healt...,natural-health
23,WELLNESS,"Woman, Deconstructed",https://www.huffingtonpost.com/entry/becoming-...,"Whatever challenges you may be experiencing, i...",becoming-fearless
24,WELLNESS,"TV, Computer Ownership Linked With Obesity And...",https://www.huffingtonpost.com/entry/tv-comput...,"Owning TVs, computers and cars is associated w...",tv-computer-obesity-diabetes-low-income-countries
25,WELLNESS,I Lost Weight: Debbie Shafer Set Small Goals A...,https://www.huffingtonpost.com/entry/i-lost-we...,"For more on weight loss, click here. Breaking ...",i-lost-weight-debbie-shafer
26,WELLNESS,Coca-Cola Makes You Thin?,https://www.huffingtonpost.com/entry/coca-cola...,You would think that half a century would be e...,coca-cola-ad
27,WELLNESS,10 Of The Best Yoga Poses For Sleep,https://www.huffingtonpost.com/entry/yoga-for-...,That's where yoga comes in. By lowering stress...,yoga-for-sleep
28,WELLNESS,I Lost Weight: A Health Scare Forced Dr. Lee C...,https://www.huffingtonpost.com/entry/i-lost-we...,Check out more of our inspiring weight loss st...,i-lost-weight-dr-lee-coleman-jr
29,WELLNESS,Choice Theory,https://www.huffingtonpost.com/entry/choice-th...,"The Times ran the obit of William Glasser (""Wi...",choice-theory

In [4]:
data_news['category'].nunique()

10

In [5]:
data_news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   category           50000 non-null  object
 1   headline           50000 non-null  object
 2   links              50000 non-null  object
 3   short_description  50000 non-null  object
 4   keywords           47332 non-null  object
dtypes: object(5)
memory usage: 1.9+ MB

In [6]:
data_news.isnull().sum()

category                0
headline                0
links                   0
short_description       0
keywords             2668
dtype: int64

In [7]:
print( data_news['category'].unique())

['WELLNESS' 'POLITICS' 'ENTERTAINMENT' 'TRAVEL' 'STYLE & BEAUTY'
 'PARENTING' 'FOOD & DRINK' 'WORLD NEWS' 'BUSINESS' 'SPORTS']

In [8]:
cooo=data_news['category']=='WORLD NEWS'

In [9]:
cooo.sum()

5000

In [10]:
data2 = data_news[['category', 'headline', 'short_description', 'keywords']]

In [11]:
data2.head()

,category,headline,short_description,keywords
0,WELLNESS,143 Miles in 35 Days: Lessons Learned,Resting is part of training. I've confirmed wh...,running-lessons
1,WELLNESS,Talking to Yourself: Crazy or Crazy Helpful?,Think of talking to yourself as a tool to coac...,talking-to-yourself-crazy
2,WELLNESS,Crenezumab: Trial Will Gauge Whether Alzheimer...,The clock is ticking for the United States to ...,crenezumab-alzheimers-disease-drug
3,WELLNESS,"Oh, What a Difference She Made","If you want to be busy, keep trying to be perf...",meaningful-life
4,WELLNESS,Green Superfoods,"First, the bad news: Soda bread, corned beef a...",green-superfoods

In [12]:
# العثور على القيمة الأكثر شيوعًا في عمود 'keywords'
most_common_keyword = data2['keywords'].mode()[0]

# استبدال القيم المفقودة بالقيمة الأكثر شيوعًا
data2['keywords'].fillna(most_common_keyword, inplace=True)

C:\Users\mahmo\AppData\Local\Temp\ipykernel_19748\572036281.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['keywords'].fillna(most_common_keyword, inplace=True)

In [13]:
data2.isnull().sum()

category             0
headline             0
short_description    0
keywords             0
dtype: int64

In [14]:
data2.head()

,category,headline,short_description,keywords
0,WELLNESS,143 Miles in 35 Days: Lessons Learned,Resting is part of training. I've confirmed wh...,running-lessons
1,WELLNESS,Talking to Yourself: Crazy or Crazy Helpful?,Think of talking to yourself as a tool to coac...,talking-to-yourself-crazy
2,WELLNESS,Crenezumab: Trial Will Gauge Whether Alzheimer...,The clock is ticking for the United States to ...,crenezumab-alzheimers-disease-drug
3,WELLNESS,"Oh, What a Difference She Made","If you want to be busy, keep trying to be perf...",meaningful-life
4,WELLNESS,Green Superfoods,"First, the bad news: Soda bread, corned beef a...",green-superfoods

In [15]:
data2.to_csv(r"C:\Users\mahmo\Downloads\Compressed\archive_9\NewsCategorizer_modified.csv", index=False, encoding='ISO-8859-1')